name: Release
on:
  push:
    tags:
    - v3.*
jobs:
  release:
    uses: rabbitmq/rabbitmq-lvc-exchange/.github/workflows/plugin-release.yml@main
    with:
      bazel_otp_name: 25
      plugin_name: rabbitmq_delayed_message_exchange
